### ISSUE TITLE
Split separate projects into their own packages

### ISSUE THREAD

**Issue by bdashore3** [bdashore3/MangaUpdates#3]
This is required to package the client side setup wizard and backup into executables for anyone to execute without having nodejs installed.

**Comment by kingbri1** [comment]
Checklist for this issue:
- [x] Convert repository into a Monorepo of server and setup packages
- [x] Fix type errors that show up from monorepo conversion
- [x] Add the pkg utility to package the setup wizards into executable files
- [x] Add a github action to auto-package the setup wizard on release

**Comment by kingbri1** [comment]
Closed by #9
